apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- cert-manager-kustomization.yaml
- trust-manager-kustomization.yaml
- trust-manager-resources-kustomization.yaml
- linkerd-kustomization.yaml
- backstage-kustomization.yaml