apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: trust-manager-resources
  namespace: flux-system
spec:
  dependsOn:
    - name: trust-manager
  interval: 1h
  path: ./infrastructure/resources/trust-manager/linkerd
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system